default: &default
  adapter: mysql
  encoding: utf8
  pool: 5
  username: root
  password: bandana
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: farwest_tourism_development

test:
  <<: *default
  database: farwest_tourism_test

production:
  <<: *default
  database: farwest_tourism_production
  username: farwest_tourism
  password: <%= ENV['FARWEST_TOURISM_DATABASE_PASSWORD'] %>
