# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc1ee94e93f2660a51ce350133041a24e71cdcbfef0ed7bd4a60c4062ea45d2c610be707063778a696ebf385f8dd3db1597339cc61f371c5cb91042d942afa00

test:
  secret_key_base: 655565699cf2e24c9f57e3cca8b1607570ac0bace712660374768d88e08a794499ac7c761257dc337ba097d723434124c7a134425cf18c1ef471adf96079ae44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
